### ISSUE TITLE
How to use winetricks with it?

### ISSUE THREAD

**Issue by probonopd** [ferion11/Proton_Appimage#1]
Hi @ferion11 thanks for this great project. How to use `winetricks` with it?

**Comment by ferion11** [comment]
I don't have tested it yet. But the protontricks (https://github.com/Matoking/protontricks) should work better.
Would you believe if i say that i don't have used no one app with this Appimage yet?

**Comment by ferion11** [comment]
If it's the same like the other Appimage of wine:
```
$ env WINEPREFIX=~/.proton32 sh ./winetricks
```
And you will need the links wine and wineserver (see: https://github.com/ferion11/Proton_Appimage/blob/master/README.md)

**Comment by probonopd** [comment]
> And you will need the links wine and wineserver

Thank you very much. Is there any way to do without needing those links?

**Comment by ferion11** [comment]
Only patching the winetricks.

**Comment by ferion11** [comment]
Looking at the winetricks code, maybe using the variables $WINESERVER and $WINE

**Comment by probonopd** [comment]
Thanks for the clarification, makes sense to me.
